### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by DyeffersonAz** [andreicristianpetcu/google_translate_this#22] opened 2020-01-20 23:37 UTC
Firefox doesn't let me install this.
It says that it can harm my computer, even clicking in the button to accept and continue, it says that it couldn't install because of it being able to harm my PC anyway.

**Comment by carlosnewmusic** [comment] 2020-01-22 01:23
the same happens to me

**Comment by andreicristianpetcu** [comment] 2020-01-22 04:53
duplicate of https://github.com/andreicristianpetcu/google_translate_this/issues/19

**Closed as completed by andreicristianpetcu** 2020-01-22 04:53 UTC

**Comment by 109isaque10** [comment] 2021-01-04 18:23
GUYS IF FOUND A WAY, just go to about:config and search extensions.blocklist.enabled and double click it to set it to false.
